import "./globals.css";
import type { Metadata } from "next";
import SessionProvider from "./providers/SessionProvider";

// components
import InnerLayout from "@/components/InnerLayout/InnerLayout";

// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Filmora | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body
          //className={inter.className}
          suppressHydrationWarning={true}
        >
          <InnerLayout>{children}</InnerLayout>
        </body>
      </SessionProvider>
    </html>
  );
}
